project_id = "ucjmbghkbfnknscqerfm"

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false

[functions.setup-activity-logs]
verify_jwt = false